CREATE TABLE IF NOT EXISTS emails (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
msg_id VARCHAR(255) UNIQUE,
thread_id VARCHAR(255),
from_addr VARCHAR(255),
to_addr VARCHAR(255),
subject TEXT,
body LONGTEXT,
received_at DATETIME DEFAULT CURRENT_TIMESTAMP,
status ENUM('new','processing','answered','escalated') DEFAULT 'new'
);


CREATE TABLE IF NOT EXISTS logs (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email_id BIGINT,
ts DATETIME DEFAULT CURRENT_TIMESTAMP,
level ENUM('INFO','WARN','ERROR') DEFAULT 'INFO',
event VARCHAR(255),
payload JSON NULL,
INDEX(email_id)
);


CREATE TABLE IF NOT EXISTS escalations (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email_id BIGINT,
reason TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
resolved TINYINT(1) DEFAULT 0,
human_reply LONGTEXT NULL
);